version: '3'

services:
  pg:
    image: postgres:11
    restart: always
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=qwiz
      - POSTGRES_HOST_AUTH=trust
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z

volumes:
  postgres_database:
    external: true
