name: Lint and Test

on:
  push:
    branches:
      - "feature/*"
      - "fix/*"
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npx nx lint

      - name: Test
        run: npx nx test